CSet++: test/set.cpp File Reference
set.cpp File Reference
This is the main test file of the cset library. It contains all the test needed to assure that the library works properly.
#include <vector>
#include <cassert>
#include <iostream>
#include "set.h"
Functions
int main ()
Runs all the tests.
Detailed Description
This is the main test file of the cset library. It contains all the test needed to assure that the library works properly.
This file contains the main function with asserts that every library method works as it should.
Each method gets tested with two asserts that verify that the library method returns the expected value when performing an operation.
If it doesn't then a message gets printed to the console describing the error. If this does happen open an issue on my github page.
Definition in file set.cpp.
Function Documentation
main()
int main ()
Runs all the tests.
Returns
(int) Returns 0 to specify to Meson that the tests finished correctly
Definition at line 16 of file set.cpp.
References set::contains(), set::count(), set::diff(), set::intersection(), set::sdiff(), set::sunion(), and set::unique().